### ISSUE TITLE
Error when trying to play videos on demand

### ISSUE THREAD

**Issue by regisfrias** [aajanki/plugin.video.yleareena.jade#5]
## The problem

For a few days now I haven't been able to play videos on demand. Live TV works fine.

## Steps to reproduce

- Open the addon
- Select "search" (or select a saved search)
- Search for something
- You should get an error

## Kodi logs

```
2024-06-24 20:57:49.964 T:38075   error <general>: GetDirectory - Error getting plugin://plugin.video.yleareena.jade/?action=search_page&keyword=isot%20koneet&offset=0&page_size=30&update_search_history=true
2024-06-24 20:57:49.975 T:1100    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.yleareena.jade/?action=search_page&keyword=isot%20koneet&offset=0&page_size=30&update_search_history=true) failed
2024-06-24 20:58:19.417 T:1225     info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 100.
2024-06-24 20:58:58.162 T:1100    error <general>: Control 52 in window 10025 has been asked to focus, but it can't
2024-06-24 20:59:19.421 T:1225     info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 110.
2024-06-24 20:59:22.290 T:1100     info <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2024-06-24 20:59:34.846 T:38100   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'requests.exceptions.HTTPError'>
Error Contents: 403 Client Error: Forbidden for url: https://areena.api.yle.fi/v1/ui/search?app_id=areena_web_personal_prod&app_key=6c64d890124735033c50099ca25dd2fe&client=yle-areena-web&language=fi&v=9&episodes=true&packages=true&query=a&service=tv&offset=0&limit=30
Traceback (most recent call last):
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/main.py", line 352, in <module>
router(sys.argv[2])
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/main.py", line 333, in router
do_search_query()
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/main.py", line 182, in do_search_query
show_search_result_page(keyword)
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/main.py", line 192, in show_search_result_page
searchresults = areena.search(keyword, offset, page_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/resources/lib/areena.py", line 120, in search
search_response = _get_search_results(keyword, offset, page_size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/plugin.video.yleareena.jade/resources/lib/areena.py", line 126, in _get_search_results
r.raise_for_status()
File "[ !!!!!REDACTED!!!!!! ].kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://areena.api.yle.fi/v1/ui/search?app_id=areena_web_personal_prod&app_key=6c64d890124735033c50099ca25dd2fe&client=yle-areena-web&language=fi&v=9&episodes=true&packages=true&query=a&service=tv&offset=0&limit=30
-->End of Python script error report<--

2024-06-24 20:59:34.985 T:38099   error <general>: GetDirectory - Error getting plugin://plugin.video.yleareena.jade/?action=search_input
2024-06-24 20:59:34.990 T:1100    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.yleareena.jade/?action=search_input) failed
```

**Comment by aajanki** [comment]
Can  you try updating the plugin? Search should work on version 1.4.0.

**Comment by regisfrias** [comment]
It works! Kiitos!
